---
- hosts: contao
  tasks:
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: ensure database exists
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="mysql" exists="true"
  - name: download contao tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: wget https://download.contao.org/3.5.4/tar chdir="/tmp/"
  - name: extract tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mkdir contao chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: extract tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: tar -xvzf /tmp/tar -C contao --strip-components=1 chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: move to www
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: rm -rf www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: move to www
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mv contao www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
